# Global properties
separator=true
separator_block_width=5
command=scripts/$BLOCK_NAME

[memory]
interval=5
label= 

[brightness]
command=brightnessctl | awk 'NR==2 { print $4 }' | cut -c 2-4
interval=once
signal=2
label= 

[volume]
interval=once
signal=1

[battery]
interval=repeat

[network]
interval=1
label=

[date]
interval=1
label= 
