#!/bin/bash

dbus-monitor --system "type='signal',interface='org.freedesktop.NetworkManager'" | \
while read -r line; do
	if [[ $line =~ (StateChanged|DeviceAdded|DeviceRemoved) ]]; then
		pkill -SIGRTMIN+12 i3blocks
		echo "status" | i3msg -t command >/dev/null
	fi
done
