#!/bin/bash

case "$BLOCK_BUTTON" in
	"1") pavucontrol & ;;
esac

VOLUME=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{ print $5 }' | head -c -3)
MUTE=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{ print $2 }')
ICON=""

if [[ $MUTE == 'no' ]]; then
	if [[ $VOLUME -lt 5 ]]; then
		ICON=" "
	elif [[ $VOLUME -le 30 ]]; then
		ICON=" "
	else
		ICON=" "
	fi
else 
	ICON=" "
fi

printf "%s %s%%\n%s " $ICON $VOLUME $ICON
