bar {
	id main-bar
	i3bar_command i3bar --transparency
	
	colors {
		background #282A36CC
		statusline #F8F8F2
		separator  #44475A

		focused_workspace  #44475A #44475A #F8F8F2
		active_workspace   #282A36 #44475A #F8F8F2
		inactive_workspace #282A36 #282A36 #BFBFBF
		urgent_workspace   #FF5555 #FF5555 #F8F8F2
		binding_mode       #FF5555 #FF5555 #F8F8F2
	}

	separator_symbol "║"
	position Top
	padding 0 5px	

	output primary
	
	status_command i3blocks -c ~/.config/i3blocks/i3blocks.conf
}

bar {
	id secondary-bar
	i3bar_command i3bar --transparency

	colors {
		background #282A36CC
		statusline #F8F8F2
		separator  #44475A

		focused_workspace  #44475A #44475A #F8F8F2
		active_workspace   #282A36 #44475A #F8F8F2
		inactive_workspace #282A36 #282A36 #BFBFBF
		urgent_workspace   #FF5555 #FF5555 #F8F8F2
		binding_mode       #FF5555 #FF5555 #F8F8F2
	}

	separator_symbol "║"
	position Top
	padding 0 5px	

	output nonprimary
	
	status_command i3blocks -c ~/.config/i3blocks/i3blocksnp.conf
}

