#!/bin/bash

DEVICE=${1:-wlan0}

CURR_SSID=$(iwctl station $DEVICE show | sed -n 's/^\s*Connected\snetwork\s*\(\S*\)\s*$/\1/p')
IW_NETWORKS+=$(iwctl station $DEVICE get-networks | sed '/^--/d')
IW_NETWORKS=$(echo "$IW_NETWORKS" | sed 1,4d)
IW_NETWORKS=$(echo "$IW_NETWORKS" | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g")
IFS=$'\n'
PREFIX=$'SSID                              SECURITY  \n'
NETWORK_LIST=""
while IFS= read -r line; do
	line=${line:4}
	SSID_NAME=$(echo "$line" | sed 's/\(\s*psk.*\)//')
	printf -v pad %34s
	line=$SSID_NAME$pad
	line=${line:0:34}
	line+=$'PSK'
	printf -v pad %45s
	line=$line$pad
	line=${line:0:45}
	line+=$'\n'
	if [ "$SSID_NAME" = "$CURR_SSID" ]; then
		PREFIX+=$line
	else
		NETWORK_LIST+=$line
	fi
done <<< "$IW_NETWORKS"
IW_NETWORKS=$(echo "$PREFIX$NETWORK_LIST" | sed '$d')
printf $IW_NETWORKS
